import type { Metadata } from "next";
import { DM_Sans, Inter, Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--roboto",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(roboto.variable, dmSans.variable)}>{children}</body>
    </html>
  );
}
